# Generated by Django 4.1 on 2022-08-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='my_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
