# Generated by Django 4.1 on 2022-08-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('state', models.CharField(choices=[('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana'), ('Goa', 'Goa'), ('Kerala', 'Kerala')], max_length=255)),
                ('pin', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('job_city', models.CharField(max_length=255)),
                ('profile_img', models.ImageField(blank=True, upload_to='my_images')),
                ('file', models.FileField(blank=True, upload_to='my_files')),
            ],
        ),
    ]
